* Refs for spesialpensum
** Game AI - techniques
1. Intelligent Agents in Computer Games
   https://www.aaai.org/Papers/AAAI/1999/AAAI99-143.pdf
2. Isla02 - Isla, D. and Blumberg, B., "New Challenges for Character-Based AI in
   Games," Artificial Intelligence and Interactive Entertainment: Papers from
   the 2002 AAAI Spring Symposium, AAAI Press, 2002
   https://www.aaai.org/Papers/Symposia/Spring/2002/SS-02-01/SS02-01-009.pdf
3. [Mateas02] Mateas, M. and Stern, A., “A Behavior Language for Story-based
   Believable Agents,”
   http://www-2.cs.cmu.edu/~michaelm/publications/AI-IE2002.pdf
4. Efficient, Realistic NPC Control Systems using Behavior-Based Techniques
   http://www.aaai.org/Papers/Symposia/Spring/2002/SS-02-01/SS02-01-010.pdf
5. Orkin03 - Orkin, J., "Applying Goal-Oriented Action Planning to Games," AI
   Game Programming Wisdom 2, Charles River Media, 2003
6. Motivated Reinforcement Learning for Non-Player Characters in Persistent
   Computer Game Worlds
   http://portal.acm.org/citation.cfm?id=1178828
7. Games, computers, and artificial intelligence
   http://www.acso.uneb.br/marcosimoes/Arquivos/IA/sdarticle_games.pdf
** Game AI - entertainment
1. Symbolic Representation of Game World State: Toward Real-Time Planning in
   Games
   http://www.aaai.org/Papers/Workshops/2004/WS-04-04/WS04-04-006.pdf
2. AI in computer games: generating interesting interactive opponents by the use
   of evolutionary computation
   http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.60.6998&rep=rep1&type=pdf
3. Adaptive Game AI
   http://www.computerscience.nl/docs/vakken/mgmag/Adaptive%20Game%20AI%202010.pdf
4. AI in Computer Games: Generating Interesting Interactive Opponents by the use
   of Evolutionary Computation
   http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.60.6998&rep=rep1&type=pdf
5. TOWARDS OPTIMIZING ENTERTAINMENT IN COMPUTER GAMES
   http://www.mip.sdu.dk/~georgios/AAI.pdf
6. Maintaining optimal challenge in computer games through real-time
   physiological feedback
   http://research.vuse.vanderbilt.edu/rasl/PDF%20files/HCI_Pramila.pdf
7. Difficulty scaling of AI
   http://www.nici.ru.nl/~idak/publications/papers/SpronckGAMEON2004.pdf
8. Evolving opponents for interesting interactive computer games
   http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.60.6629&rep=rep1&type=pdf
9. Real-time game adaptation for optimizing player satisfaction
   http://www.itu.dk/people/yannakakis/TCIAIG_RealTimeAdaptation.pdf
10. How to model and augment player satisfaction: A review
    http://www.itu.dk/people/yannakakis/wocci.pdf
** Automated programming / ADATE
1. Genetic Programming and Emergent Intelligence
   http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.15.5594&rep=rep1&type=pdf
2. J. R. Olsson, Inductive functional programming using incremental program
   transformation and Execution of logic programs by iterative-deepening A*
   SLD-tree search, Research report 189, Dr scient thesis, ISBN 82-7368-099-1,
   University of Oslo, October 1994.
3. J. R. Olsson, Inductive functional programming using incremental program
   transformation, Artificial Intelligence, volume 74, number 1, March 1995,
   pp. 55-83.
4. J. R. Olsson, Population management for automatic design of algorithms through
   evolution, International Conference on Evolutionary Computation, IEEE Press,
   1998.
5. J. R. Olsson, The art of writing specifications for the ADATE automatic
   programming system, Genetic Programming 1998, Morgan Kaufmann.
6. J. R. Olsson and B. Wilcox, Self-Improvement for the ADATE Automatic Programming
   System, A more preliminary version of this paper was published at the 3rd
   WSES International Conference on Evolutionary Computation, WSES Press, 2002.
7. J.R. Olsson and D. M. W. Powers, Machine Learning of Human Language through
   Automatic Programming, International Conference on Cognitive Science,
   University of New South Wales, July 2003, pp. 507-512.
* Notes on methodology
** Experimentation platform
   Should the game used as a basis for the research be pre-made, or is one to be
   created alongside the research?

   Pros to using pre-made:
   - Little-to-no time wasted on implementation issues
   - Better tested and more functional than a homegrown solution

   Cons to using pre-made:
   - Might not support everything we want in AI programming
   - Might be hard to find something simple enough to make the project feasible

   A third option is hacking an existing solution to support what we want.
** How to measure results
   Since the aim of the project is to measure how engaging or fun an AI is to
   play with, it might be hard to find a reliable way to measure this. The
   method most used outside of academia is user testing, but this might be hard
   to pull off, takes time, and lacks rigour. Another method is to set up
   certain criteria by which to measure "fun," and apply those to the AI's
   performance to get our results.

   Ultimately the difficulty lies with finding a balance between practical
   application of the research results and the academic value of the research,
   and this has to be found by deciding how close to align oneself with the
   methods of each "camp".

   Most crucially, the question of whether generated AI is even distinguishable
   from a reasonable well created "static", complex AI, and if the added
   overhead and lack of control is even worth it, must be answered.
** How to drive the AI
   Should the code being generated be the sole driver of the NPC's AI, possibly
   having been derived from a few selections of "decent" pre-programmed AIs that
   exhibit certain "Classes of behaviour"; Or should the AI being generated
   instead make use of existing AI frameworks and algorithms?

   The benefit of using existing frameworks and algorithms would lie in allowing
   much more complex AI to be utilized, at a much higher performance than
   anything that could be produced during the course of the project.

   The downside is that it will be much harder to accomodate for the intricacies
   of existing solutions in the scope of automated programming. This is perhaps
   a side-point to be explored when evaluating the usefulness of automated
   programming for NPC behaviour. Another downside is that it might be harder to
   compare the performance of premade NPCs and generated NPCs when their
   behaviour grows more complex, so sticking to a simple self-grown AI code
   might be a better idea for simpler analysis of results.
